version: "3"

tasks:
  build:
    desc: Build the rulem CLI binary
    cmds:
      - go build -o rulem ./cmd/rulem

  run:
    desc: Run the rulem CLI interactively
    cmds:
      - DEBUG=1 go run ./cmd/rulem

  test:
    desc: Run all unit tests
    cmds:
      - go test --cover ./...

  lint:
    desc: Run golangci-lint on the codebase
    cmds:
      - |
        if ! command -v golangci-lint >/dev/null 2>&1; then
          echo 'golangci-lint not found. Installing...';
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest;
        fi
        golangci-lint run ./...

  tidy:
    desc: Clean up go.mod and go.sum
    cmds:
      - go mod tidy

  clean:
    desc: Remove built binaries and temporary files
    cmds:
      - rm -f rulem

  dev:
    desc: Build, lint, and test in sequence
    deps: [tidy, lint, test, build]
